name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ivanvc/abuild-releaser-action@v1.2.0
        with:
          author: Robert Maerz <171489683+r-maerz@users.noreply.github.com>
          rsa_public_key: ${{ secrets.RSA_PUBLIC_KEY }}
          rsa_private_key: ${{ secrets.RSA_PRIVATE_KEY }}
          package_dirs: "main/*"
          alpine_branch: "v3.22"
